src/Proton/RigbagBundle/Entity/User.php
<?php

namespace Proton\RigbagBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Proton\RigbagBundle\Entity\User
 */
class User
{

    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var string $name
     */
    private $name;

    /**
     * @var string $bio
     */
    private $bio;

    /**
     * @var string $phone
     */
    private $phone;

    /**
     * @var string $post_code
     */
    private $post_code;

    /**
     * @var string $email
     */
    private $email;

    /**
     * @var string $facebook_id
     */
    private $facebook_id;

    /**
     * @var string $twitter_id
     */
    private $twitter_id;

    /**
     * @var string $google_id
     */
    private $google_id;

    /**
     * @var string $profile_picture
     */
    private $profile_picture;

    /**
     * @var string $location
     */
    private $location;

    /**
     * @var string $location_country_code
     */
    private $location_country_code;

    /**
     * @var string $state
     */
    private $state;

    /**
     * @var \DateTime $created_at
     */
    private $created_at;

    /**
     * @var \DateTime $updated_at
     */
    private $updated_at;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    private $interests;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    private $options;



    public function hasCircle( $circle ) {

    	if( is_object( $circle ) ) {
    		$circle = $circle->getId();
    	}

    	$has = false;
    	foreach( $this->getCircles() as $c ) {
    		if( $c->getId() == $circle ) {
    			$has = true;
    			break;
    		}
    	}

    	return $has;
    }

    /**
     * 0			- UNKNOW TYPE
     * 1			- OK (FREE)
     * 2			- OK (ANNUAL SUBSCRIBED)
     * 10			- ANNUAL (NEVER PAID)
     * 11			- ANNUAL (EXPIRED)
     */
    public function getAccountState()
    {

    	switch( $this->getAccountType() )
    	{
    		case 'free':
    			return 1;
    		break;
    		case 'annual':
    			if( $this->getExpiredAt() == null ) {
    				return 10;
    			} elseif ( $this->getExpiredAt()->getTimestamp() < time() ) {
    				return 11;
    			}
    			return 2;
    		break;
    	}

    	return 0;
    }

    public function getOptionValue( $key, $defaultValue = null ) {
    	$options		= $this->getOptions();

    	$defaultValue	= null;
    	if( is_null( $options ) || !count( $options ) ) {
    		return $defaultValue;
    	}
    	foreach( $options as $option ) {
    		if( $option->getOptionKey() == $key ) {
    			return $option->getOptionValue();
    		}
    	}

    	return $defaultValue;
    }

    public function getDisplayName() {
    	return $this->getName();
    }

    public static function encodeHash( $userId ) {
    	$tpl	= '000000000';
    	return substr( $tpl, 0, strlen( $userId ) ) . $userId;
    }

    public static function decodeHash( $userHash ) {
    	while( substr( $userHash, 0, 1 ) == '0' ) {
    		$userHash = substr( $userHash, 1 );
    	}
    	return $userHash;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->interests = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return User
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set bio
     *
     * @param string $bio
     * @return User
     */
    public function setBio($bio)
    {
        $this->bio = $bio;

        return $this;
    }

    /**
     * Get bio
     *
     * @return string
     */
    public function getBio()
    {
        return $this->bio;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return User
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set post_code
     *
     * @param string $postCode
     * @return User
     */
    public function setPostCode($postCode)
    {
        $this->post_code = $postCode;

        return $this;
    }

    /**
     * Get post_code
     *
     * @return string
     */
    public function getPostCode()
    {
        return $this->post_code;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set facebook_id
     *
     * @param string $facebookId
     * @return User
     */
    public function setFacebookId($facebookId)
    {
        $this->facebook_id = $facebookId;

        return $this;
    }

    /**
     * Get facebook_id
     *
     * @return string
     */
    public function getFacebookId()
    {
        return $this->facebook_id;
    }

    /**
     * Set twitter_id
     *
     * @param string $twitterId
     * @return User
     */
    public function setTwitterId($twitterId)
    {
        $this->twitter_id = $twitterId;

        return $this;
    }

    /**
     * Get twitter_id
     *
     * @return string
     */
    public function getTwitterId()
    {
        return $this->twitter_id;
    }

    /**
     * Set google_id
     *
     * @param string $googleId
     * @return User
     */
    public function setGoogleId($googleId)
    {
        $this->google_id = $googleId;

        return $this;
    }

    /**
     * Get google_id
     *
     * @return string
     */
    public function getGoogleId()
    {
        return $this->google_id;
    }

    /**
     * Set profile_picture
     *
     * @param string $profilePicture
     * @return User
     */
    public function setProfilePicture($profilePicture)
    {
        $this->profile_picture = $profilePicture;

        return $this;
    }

    /**
     * Get profile_picture
     *
     * @return string
     */
    public function getProfilePicture()
    {
        return $this->profile_picture;
    }

    /**
     * Set location
     *
     * @param string $location
     * @return User
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set location_country_code
     *
     * @param string $locationCountryCode
     * @return User
     */
    public function setLocationCountryCode($locationCountryCode)
    {
        $this->location_country_code = $locationCountryCode;

        return $this;
    }

    /**
     * Get location_country_code
     *
     * @return string
     */
    public function getLocationCountryCode()
    {
        return $this->location_country_code;
    }

    /**
     * Set state
     *
     * @param string $state
     * @return User
     */
    public function setState($state)
    {
        $this->state = $state;

        return $this;
    }

    /**
     * Get state
     *
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Set created_at
     *
     * @param \DateTime $createdAt
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updated_at
     *
     * @param \DateTime $updatedAt
     * @return User
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Add interests
     *
     * @param Proton\RigbagBundle\Entity\Interest $interests
     * @return User
     */
    public function addInterest(\Proton\RigbagBundle\Entity\Interest $interests)
    {
        $this->interests[] = $interests;

        return $this;
    }

    /**
     * Remove interests
     *
     * @param Proton\RigbagBundle\Entity\Interest $interests
     */
    public function removeInterest(\Proton\RigbagBundle\Entity\Interest $interests)
    {
        $this->interests->removeElement($interests);
    }

    /**
     * Get interests
     *
     * @return Doctrine\Common\Collections\Collection
     */
    public function getInterests()
    {
        return $this->interests;
    }

	/**
     * Check for user interest
     *
     * @return boolean
     */
	public function hasInterest(\Proton\RigbagBundle\Entity\Interest $interest) 
	{
		if( is_object( $interest ) ) {
    		$interestId = $interest->getId();
    	}
		
		foreach ($this->interests as $currentInterest) {
			if ($currentInterest->getId() == $interestId) {
				return true;
				break;
			}
		}
		return false;
	}

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
    	$this->created_at	= new \DateTime();
    }

    /**
     * @ORM\PrePersist
     */
    public function setUpdatedAtValue()
    {
    	$this->updated_at	= new \DateTime();
    }
    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    private $adverts;


    /**
     * Add adverts
     *
     * @param Proton\RigbagBundle\Entity\Advert $adverts
     * @return User
     */

src/Proton/RigbagBundle/Resources/views/User/_content-subscription.html.twig.twig
{% if user.accountState == 0 or user.accountState == 1 or user.accountState == 10 or user.accountState == 11 %}
<div class="span10">
	<p class="al-center">{% trans %}Please select subscription type:{% endtrans %}</p>
	<div class="or">or</div>
</div>
<div class="clearfix"></div>
<!-- COLUMN LEFT: start -->
<div class="span5">
	<div class="column-left border-space">
		<h2>Annual subscription</h2>
		<p><span class="price-intro"><span class="price-old">&euro;60</span> {% trans %}FREE{% trans %}</span> {% trans %}while in beta{% endtrans %} <br><span class="inlinehint">{% trans %}(you won't be paying for the whole year){% endtrans %}</span></p>
		<div class="subscription-select subscription-annual">
			<a href="{{ path('payments_subscription', { type: 'annual' }) }}" title="" class="btn">Select</a>
			<!-- <p>{% trans %}You will be redirected{% endtrans %}</p>
			<p>{% trans %}to PayPal to pay{% endtrans %} &euro;30</p> -->
		</div>
		<div class="clearfix"></div>
		<p><strong>{% trans %}Benefits of the annual subscription:{% endtrans %}</strong></p>
		<ul>
			<li>{% trans %}Sell as much gear as you like for a full year{% endtrans %}</li>
			<li>{% trans %}Buy or swap new or secondhand gear{% endtrans %}</li>
			<li>{% trans %}Read all the latest news{% endtrans %}</li>
			<li>{% trans %}Connect with athletes and companies in your sport{% endtrans %}</li>
			<li>{% trans %}The most cost effective way of getting all the benefits of RigBag{% endtrans %}</li>
		</ul>
	</div>
</div>
<!-- COLUMN LEFT: end -->
<!-- COLUMN RIGHT: start -->
<div class="span5">
	<div class="column-right border-space">
		<h2>{% trans %}Pay as you go{% endtrans %}</h2>
		<p>{% trans %}You will be charged{% endtrans %} <span class="price-intro-small">&euro;5</span> {% trans %}for each advert you post on RigBag{% endtrans %}</p>
        <div class="subscription-select subscription-free">
			<a href="#" title="" class="btn">Select</a>
		</div>
		<div class="clearfix"></div>
		<p><strong>{% trans %}Pay as you go subscription:{% endtrans %}</strong></p>
		<ul>
			<li>{% trans %}Try out RigBag for a low cost{% endtrans %}</li>
			<li>{% trans %}Post an advert{% endtrans %}</li>
			<li>{% trans %}Ideal if you just want to see if RigBag is for you{% endtrans %}</li>
		</ul>
	</div>
</div>
<!-- COLUMN RIGHT: end -->
<script>
$(document).ready( function() {

	
	$('.subscription-free .btn').click( function() {
		
		{% if signup %}
			rbApp.callAction( 'profile/subscription/select/free/', 'setUrl(\'/signup/done/\')' );
		{% else %}
			rbApp.callAction( 'profile/subscription/select/free/' );
		{% endif %}
		return false;
	});

});
</script>
{% else %}
<div class="span9 offset1">
	{% trans %}Account type: Annual{% endtrans %}<br/>
	{% trans %}Expire date:{% endtrans %} {{ user.expiredAt|date('d.m.Y') }}
</div>
{% if signup %}
<div class="clearfix"></div>
<div class="actions">
		<a href="#" title="" class="btn">{% trans %}Next{% endtrans %} &raquo;</a>
</div>
{% endif %}
<script>
$(document).ready( function() {
	$('.actions .btn').click( function() {
		setUrl( '/signup/done/' );
		return false;
	});
});
</script>
{% endif %}

src/Proton/RigbagBundle/Resources/views/User/content-signup-done.html.twig
<div class="span9 offset1">
	<h2 style="font-weight: 400; margin-bottom: 10px;">{% trans %}Nice work!!!{% endtrans %}</h2>
	<h4>{% trans %}Your account is ready. Now you can publish your adverts.{% endtrans %}</h4>
	
	<div style="margin-top: 40px;">
		<a href="{{ path('start') }}" title="" class="btn">{% trans %}Next{% endtrans %} &raquo;</a>
	</div>
</div>

src/Proton/RigbagBundle/Resources/views/User/content-subscription.html.twig
<div class="span9 offset1">
	<h2 style="font-weight: 400; margin-bottom: 10px;">{% trans %}Beta version is FREE{% endtrans %}</h2>
{% if signup %}
	<div style="margin-top: 40px;">
		<a href="#" title="" class="btn btn-sub">{% trans %}Next{% endtrans %} &raquo;</a>
	</div>
{% endif %}
</div>
<script>
$(document).ready( function() {

	$('.btn-sub').click( function() {
		{% if signup %}
			rbApp.callAction( 'profile/subscription/select/free/', 'setUrl(\'/signup/done/\')' );
		{% endif %}
		return false;
	});
})
</script>

src/Proton/RigbagBundle/Resources/views/User/content-transactions.html.twig
<div class="span10">
{% if transactions %}
<table class="table table-bordered">
<thead>
	<tr>
		<th class="cell-thumb"></th>
		<th class="cell-date-time">{% trans %}date &amp; time{% endtrans %}</th>
		<th class="cell-type">{% trans %}type{% endtrans %}</th>
		<th class="cell-description">{% trans %}description{% endtrans %}</th>
		<th class="cell-amount">{% trans %}amount{% endtrans %}</th>
		<th class="cell-state">{% trans %}state{% endtrans %}</th>
	</tr>
</thead>
<tbody>
{% for transaction in transactions %}
<tr>
	<td class="cell-thumb">
		{% if transaction.advertId %}
			<div class="ico"{% if transaction.advert.mainImage != null %} style="background-image: url({{ mediaUrl }}{{ transaction.advert.mainImage.path|replace({'%size%': '160x160' }) }});"{% endif %}></div>
		{% else %}
			&nbsp;
		{% endif %}
	</td>
	<td class="cell-date-time">
		{{ transaction.createdAt|date('d.m.Y') }}<br/>
		{{ transaction.createdAt|date('H:i') }}
	</td>
	<td class="cell-type">
		{{ transaction.typeLabel( user.id ) }}
	</td>
	<td class="cell-description">
		{% if transaction.type == 'advert' %}
			{% if transaction.advertId %}
				{% trans %}Advert no.{% endtrans %} {{ transaction.advertId }}: <a href="#" onclick="setUrl( '#/adverts/view/{{ transaction.advert.hash }}/' ); return false;">{{ transaction.advert.title}}</a><br/>
				{% if transaction.advert.mode == 'sale' %}{% trans %}FOR SALE{% endtrans %}{% endif %}
			{% else %}
				{{ transaction.description }}
			{% endif %}
		{% elseif transaction.type == 'buy' %}
			{% if transaction.advertId %}
				{% trans %}Advert no.{% endtrans %} {{ transaction.advertId }}: <a href="#" onclick="setUrl( '#/adverts/view/{{ transaction.advert.hash }}/' ); return false;">{{ transaction.advert.title}}</a>
				<hr/>
				{% if transaction.fromUserId == user.id %}
					{{ transaction.toUserName }}<br/>
					<span>{% trans %}email:{% endtrans %}</span> <a href="mailto:{{ transaction.toUserEmail }}">{{ transaction.toUserEmail }}</a>
					{% if transaction.toUserId %}, <span>{% trans %}phone:{% endtrans %}</span> {% if transaction.toUser.phone %}{{ transaction.toUser.phone }}{% else %}-{% endif %}{% endif %}
					{% if transaction.toUserId %}<br/><span>{% trans %}address:{% endtrans %}</span> {% if transaction.toUser.locationFormated %}{{ transaction.toUser.locationFormated }}{% else %}-{% endif %}{% endif %}
				{% else %}
					{{ transaction.fromUserName }}<br/>
					<span>{% trans %}email:{% endtrans %}</span> <a href="mailto:{{ transaction.fromUserEmail }}">{{ transaction.fromUserEmail }}</a>
					{% if transaction.fromUserId %}, <span>{% trans %}phone:{% endtrans %}</span> {% if transaction.fromUser.phone %}{{ transaction.fromUser.phone }}{% else %}-{% endif %}{% endif %}
					{% if transaction.fromUserId %}<br/><span>{% trans %}address:{% endtrans %}</span> {% if transaction.fromUser.locationFormated %}{{ transaction.fromUser.locationFormated }}{% else %}-{% endif %}{% endif %}
				{% endif %}
			{% else %}
				{{ transaction.description }}
			{% endif %}
		{% elseif transaction.type == 'swap' %}
			{% if transaction.advertId %}
				{% trans %}Advert no.{% endtrans %} {{ transaction.advertId }}: <a href="#" onclick="setUrl( '#/adverts/view/{{ transaction.advert.hash }}/' ); return false;">{{ transaction.advert.title}}</a><br/>
				<span>{% trans %}swap for:{% endtrans %}</span> {{ transaction.advert.swapFor }}
				<hr/>
				{% if transaction.fromUserId == user.id %}
					{{ transaction.toUserName }}<br/>
					<span>{% trans %}email:{% endtrans %}</span> <a href="mailto:{{ transaction.toUserEmail }}">{{ transaction.toUserEmail }}</a>
					{% if transaction.toUserId %}, <span>{% trans %}phone:{% endtrans %}</span> {% if transaction.toUser.phone %}{{ transaction.toUser.phone }}{% else %}-{% endif %}{% endif %}
					{% if transaction.toUserId %}<br/><span>{% trans %}address:{% endtrans %}</span> {% if transaction.toUser.locationFormated %}{{ transaction.toUser.locationFormated }}{% else %}-{% endif %}{% endif %}
				{% else %}
					{{ transaction.fromUserName }}<br/>
					<span>{% trans %}email:{% endtrans %}</span> <a href="mailto:{{ transaction.fromUserEmail }}">{{ transaction.fromUserEmail }}</a>
					{% if transaction.fromUserId %}, <span>{% trans %}phone:{% endtrans %}</span> {% if transaction.fromUser.phone %}{{ transaction.fromUser.phone }}{% else %}-{% endif %}{% endif %}
					{% if transaction.fromUserId %}<br/><span>{% trans %}address:{% endtrans %}</span> {% if transaction.fromUser.locationFormated %}{{ transaction.fromUser.locationFormated }}{% else %}-{% endif %}{% endif %}
				{% endif %}
			{% else %}
				{{ transaction.description }}
			{% endif %}
		{% elseif transaction.type == 'freebie' %}
			{% if transaction.advertId %}
				{% trans %}Advert no.{% endtrans %} {{ transaction.advertId }}: <a href="#" onclick="setUrl( '#/adverts/view/{{ transaction.advert.hash }}/' ); return false;">{{ transaction.advert.title}}</a>
				<hr/>
				{% if transaction.fromUserId == user.id %}
					{{ transaction.toUserName }}<br/>
					<span>{% trans %}email:{% endtrans %}</span> <a href="mailto:{{ transaction.toUserEmail }}">{{ transaction.toUserEmail }}</a>
					{% if transaction.toUserId %}, <span>{% trans %}phone:{% endtrans %}</span> {% if transaction.toUser.phone %}{{ transaction.toUser.phone }}{% else %}-{% endif %}{% endif %}
					{% if transaction.toUserId %}<br/><span>{% trans %}address:{% endtrans %}</span> {% if transaction.toUser.locationFormated %}{{ transaction.toUser.locationFormated }}{% else %}-{% endif %}{% endif %}
				{% else %}
					{{ transaction.fromUserName }}<br/>
					<span>{% trans %}email:{% endtrans %}</span> <a href="mailto:{{ transaction.fromUserEmail }}">{{ transaction.fromUserEmail }}</a>
					{% if transaction.fromUserId %}, <span>{% trans %}phone:{% endtrans %}</span> {% if transaction.fromUser.phone %}{{ transaction.fromUser.phone }}{% else %}-{% endif %}{% endif %}
					{% if transaction.fromUserId %}<br/><span>{% trans %}address:{% endtrans %}</span> {% if transaction.fromUser.locationFormated %}{{ transaction.fromUser.locationFormated }}{% else %}-{% endif %}{% endif %}
				{% endif %}
			{% else %}
				{{ transaction.description }}
			{% endif %}
		{% elseif transaction.type == 'subscription' %}
			{% trans %}RigBag annual subscription{% endtrans %}
			{% if transaction.state == 'completed' %}
			- {% trans %}till{% endtrans %} {{ transaction.fromUser.expiredAt|date('d.m.Y') }}
			{% endif %}
		{% endif %}
	</td>
	<td class="cell-amount">
		{% if transaction.amount %}
			{% if transaction.isIncome( user.id ) %}{% else %}-{% endif %}{{ transaction.amount }} {{ transaction.currencyLabel }}
		{% else %}
		-
		{% endif %}
	</td>
	<td class="cell-state">
	 	{{ transaction.state|capitalize }}
	</td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
	<div class="alert alert-success">
    	{% trans %}You haven't any transactions.{% endtrans %}
    </div>
{% endif %}
</div>

src/Proton/RigbagBundle/Resources/views/User/panel-messages.html.twig
<ul class="messages-list">
{% set isFirst = true %}
{% if messages %}
{% for message in messages %}

<li onclick="userPanelMessageClick( {{ message.id }} ); window.location ='{% if message.advert and message.state != 'public' %}{{ path('start') }}#/adverts/view/{{ message.advert.hash }}/{% else %}{{ path('start') }}#/qa/view/{{ message.parentId }}/{% endif %}'; return false;" class="{% if isFirst ==  true %}first{% endif %}{% if message.readed != 1 %} {% trans %}unreaded{% endtrans %}{% endif %}">
	{% if message.state == 'system' %}
		<div class="ico" style="{% if message.advert and message.advert.mainImage != null %}background-image: url({{ mediaUrl }}{{ message.advert.mainImage.path|replace({'%size%': '50x50' }) }}){% endif %}"></div>
	{% else %}
		<div class="ico" style="background-image: url({{ mediaUrl }}{{ message.user.profilePicture|replace({'%size%': '40x40' }) }});"></div>
	{% endif %}
	<div class="info">
		<h5>
			{% if message.state == 'system' %}
				{% if message.advert %}
					{{ message.advert.title|slice(0, 30)|stripslashes }}
				{% else %}
					#{{ message.id }}
				{% endif %}
			{% else %}
				{{ message.user.displayName|stripslashes }}
			{% endif %}
		</h5>
		<div class="date">{{ message.createdAt|date('d.m.Y H:i') }}</div>
		<p>
			{% if message.state == 'system' %}

				{{ message.body|stripslashes }}

			{%  else %}

				{% if message.body|length > 50 %}
					{{ message.body|slice(0, 50)|stripslashes }}...
				{% else %}
					{{ message.body|stripslashes }}
				{%  endif %}

			{% endif %}

			{% if message.state != 'system' and message.advert %}
				(<strong>{{ message.advert.title|slice(0, 30)|stripslashes }}</strong>)
			{% endif %}
		</p>
	</div>
	<div class="clearfix"></div>
</li>
{% set isFirst = false %}
{% endfor %}
{% else %}
<li class="first">
	<div style="padding: 5px 6px;">{% trans %}No messages{% endtrans %}</div>
</li>
{% endif %}
</ul>

src/Proton/RigbagBundle/Resources/views/User/profile-content-adverts.html.twig
<!-- SPAN10: start -->
<div class="span10 adverts-list">
	{% if adverts or myProfile %}
	<ul id="adverts-list">
		{% if myProfile %}
		<li class="new-action" onclick="setUrl('/adverts/add/');">
			<div class="border">
				<div class="ico-add"></div>
				<h4>{% trans %}Post a new advert{% endtrans %}</h4>
			</div>
		</li>
		{% endif %}
		{% for advert in adverts %}
			{% include 'ProtonRigbagBundle:Advert:list-box.html.twig' with { 'advert': advert } %}
		{% endfor %}
	</ul>
	{% else %}
		<div class="no-items">
			No adverts
		</div>
	{% endif %}
</div>
<!-- SPAN10: end -->

src/Proton/RigbagBundle/Resources/views/User/profile-content-circles.html.twig
<div class="span10 mysports">
	<ul id="sports-list">
		{% if myProfile %}
		<li class="new-action" onclick="setUrl('/circles/browse/');">
			<div class="border">
				<div class="ico-add"></div>
				<h4>{% trans %}Browse other circles{% endtrans %}</h4>
			</div>
		</li>
		{% endif %}
		{% for circle in circles %}
		<li class="position" id="circle-{{ circle.id }}" data-id="{{ circle.id }}">
			<div class="ico" style="background-image: url({{ path('image_sport', { sportId: circle.interest.id, width: 80, height: 80 }) }});"></div>
			<div class="name">{{ circle.name|stripslashes }} ({{ circle.description|stripslashes }})</div>
			<div class="action">
				<span class="ico"></span>
			</div>
			{% if myProfile %}
			<div class="but-delete"></div>
			{% endif %}
		</li>
		{% endfor %}
	</ul>
	<script>
		$('.but-delete').click( function( event ) {
			event.stopPropagation();
			rbApp.circle.remove($(this).parent().attr('data-id'));
		});
		$('li.position').click( function() {
			setUrl('/circles/' + $(this).attr('data-id') + '/adverts/list/' );
		});
	</script>
</div>
<!-- SPAN10: end -->

src/Proton/RigbagBundle/Resources/views/User/profile-content-qa.html.twig
<!-- SPAN10: start -->
<div class="span10 q-and-a-list">
	<ul id="qa-list">
	{% if myProfile %}
		<li class="new-action" onclick="setUrl('/qa/add/' );">
			<div class="border">
				<div class="ico-add"></div>
				<h4>{% trans %}Post a new question{% endtrans %}</h4>
			</div>
		</li>
		{% endif %}
	{% for position in questions %}
		{% include 'ProtonRigbagBundle:Qa:position-main.html.twig' with { 'position': position } %}
	{% endfor %}
	</ul>
</div>
<!-- SPAN10: end -->

src/Proton/RigbagBundle/Resources/views/User/profile-header-top.html.twig
<div class="nav-left">
	<a href="#" onclick="history.back(); return false;" title="" class="back"><span></span></a>
</div>
<h1>{% if myProfile %}{% trans %}My profile{% endtrans %}{% else %}<span>{% trans %}Profile:{% endtrans %}</span> {{ user.name|stripslashes }}{% endif %}</h1>
{% if myProfile %}

{% endif %}